language: scala

sudo: required
dist: trusty
services: docker

addons:
  apt:
    packages:
      - shellcheck

before_install:
  - git fetch --tags
  - docker pull exasol/docker-db:7.0.4
  - docker pull exasol/docker-db:6.2.12-d1
  - docker network create -d bridge --subnet 192.168.0.0/24 --gateway 192.168.0.1 dockernet

matrix:
  include:
    - jdk: openjdk11
      scala: 2.12.12
      env: SPARK_VERSION="2.4.5" EXASOL_DOCKER_VERSION="6.2.12-d1"

    - jdk: openjdk11
      scala: 2.12.12
      env: SPARK_VERSION="2.4.5" EXASOL_DOCKER_VERSION="7.0.4"

    - jdk: openjdk11
      scala: 2.12.12
      env: SPARK_VERSION="3.0.1" EXASOL_DOCKER_VERSION="6.2.12-d1"

    - jdk: openjdk11
      scala: 2.12.12
      env: SPARK_VERSION="3.0.1" EXASOL_DOCKER_VERSION="7.0.4"

script:
  - travis_wait 30 ./scripts/ci.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - ./sbtx coveralls

cache:
  directories:
    - "$HOME/.sbt/1.0"
    - "$HOME/.sbt/boot/scala*"
    - "$HOME/.sbt/cache"
    - "$HOME/.sbt/launchers"
    - "$HOME/.ivy2"
    - "$HOME/.coursier"

before_cache:
  - du -h -d 1 $HOME/.ivy2/
  - du -h -d 2 $HOME/.sbt/
  - du -h -d 4 $HOME/.coursier/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
  - find $HOME/.coursier/cache -name "*.lock" -type f -delete
